version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - echo "Zipping Lambda function from source code..."
      - zip lambda_function.zip lambda_function.py
      - echo "Updating Lambda function code directly..."
      - aws lambda update-function-code --function-name TicTacToeLambda --zip-file fileb://lambda_function.zip
artifacts:
  files:
    - lambda_function.zip
