version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - echo "Zipping Lambda function from source code..."
      - zip lambda_function.zip lambda_function.py
      - echo "Updating Lambda function code directly..."
      - aws lambda update-function-code --function-name TicTacToeLambda --zip-file fileb://lambda_function.zip
  post_build:
    commands:
      - echo "Fetching WebsiteBucket name from CloudFormation outputs..."
      - WEBSITE_BUCKET=$(aws cloudformation describe-stacks --stack-name Pipeline --query "Stacks[0].Outputs[?OutputKey=='WebsiteURL'].OutputValue" --output text | sed -E 's#http://([^.]+)\.s3-website-.*#\1#')
      - echo "Uploading index.html to S3 bucket:$WEBSITE_BUCKET"
      - |
        if [ -z "$WEBSITE_BUCKET" ]; then
          echo "ERROR: WEBSITE_BUCKET is empty. Check your stack name and CloudFormation outputs."
          exit 1
        fi
      - aws s3 cp index.html s3://$WEBSITE_BUCKET/index.html
artifacts:
  files:
    - lambda_function.zip
